### ISSUE TITLE
400 Bad Request Error

### ISSUE THREAD

**Issue by sharkless** [AlexDerugo/netbox-nmap-scan#1]
I love how your system works with tagging the prefixes instead of listing them all in a file.  I am trying to get your scan to work and have added all the tags to my system but get this error. 

Traceback (most recent call last):
  File "/root/projects/netbox-nmap-scan/main.py", line 96, in <module>
    main()
  File "/root/projects/netbox-nmap-scan/main.py", line 93, in main
    del_ip_from_netbox(list_no_scan)
  File "/root/projects/netbox-nmap-scan/main.py", line 80, in del_ip_from_netbox
    if nb.ipam.ip_addresses.filter(address=ipaddr, tag = tag_VM_no_del_IP):
  File "/usr/local/lib/python3.10/dist-packages/pynetbox/core/response.py", line 135, in __len__
    self._response_cache.append(next(self.response))
  File "/usr/local/lib/python3.10/dist-packages/pynetbox/core/query.py", line 280, in get
    req = self._make_call(add_params=add_params)
  File "/usr/local/lib/python3.10/dist-packages/pynetbox/core/query.py", line 247, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'tag': ['Select a valid choice. tag_VM_no_del_IP is not one of the available choices.']}

**Comment by sharkless** [comment]
I was missing the tag "tag_VM_no_del_IP"
